name: 'bookshop_dbt'
version: '1.0.0'
config-version: 2

profile: 'bookshop'

model-paths: ['models']
target-path: 'target'
clean-targets: ['target','dbt_packages']

models:
  bookshop_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
