# version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  airflow:
    image: apache/airflow:2.9.3
    depends_on:
      - postgres
      - minio
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: UTC
    volumes:
      - ../orchestrations/airflow/dags:/opt/airflow/dags
      - ../:/opt/airflow/plugins   # <-- Sửa lại: lấy toàn bộ project làm plugins
    ports:
      - "8080:8080"
    command: bash -c "airflow db init && airflow webserver & airflow scheduler"

  app:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile   # <-- Sửa lại: Dockerfile nằm trong thư mục infrastructure
    env_file:
      - ../.env.example
    depends_on:
      - postgres
      - minio
    volumes:
      - ../:/app   # <-- Sửa lại: mount toàn bộ project
    ports:
      - "8000:8000"
    command: python tools/list_config.py

  backend:
    build:
      context: ../backend
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/bookshop
    depends_on:
      - postgres

  frontend:
    build:
      context: ../frontend
    ports:
      - "5173:5173"
    restart: always


volumes:
  pgdata:
  miniodata:
